In [1]:
import torch
import numpy as np

## 텐서 생성

텐서는 리스트, 넘파이 Array형으로부터 생성 가능

In [5]:
#파이썬 이중리스트로 텐서를 생성
data=[
    [1, 2],
    [3, 4]
]
x_data=torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [6]:
#넘파이 Array로 텐서를 생성
np_array=np.array(data)
x_np=torch.tensor(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


In [7]:
#텐서로부터 1로 가득찬 텐서 생성
x_ones=torch.ones_like(x_data)
print(x_ones)

#텐서로부터 랜덤값으로 가득찬 텐서 생성
x_rand=torch.rand_like(x_data, dtype=torch.float)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.2771, 0.1855],
        [0.1675, 0.5659]])


텐서 생성은 튜플로 지정된 행과 열의 크기에 맞게 생성 가능

In [ ]:
#튜플 안에 차원을 계속 증가시킬 수 있음
shape = (2,3,)

#텐서 생성할 때 텐서의 크기를 지정하는 인자는 size=(행, 열)
rand_tensor=torch.rand(size=shape)
ones_tensor=torch.ones(size=shape)
zeros_tensor=torch.zeros(size=shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.9435, 0.4367, 0.9892],
        [0.7394, 0.9409, 0.7235]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


텐서 속성은 다음과 같이 출력할 수 있음

In [24]:
tensor=torch.rand(size=(2,2), dtype=float, device="cuda")

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([2, 2])
Datatype of tensor: torch.float64
Device tensor is stored on: cuda:0


## 텐서 연산

In [25]:
#GPU를 호출할 때는 "cuda"라고 명시
if torch.cuda.is_available():
    tensor.to("cuda")
else:
    tensor.to("cpu")

텐서에서 특정 인덱스를 호출할 때는, 텐서이름[행:열]

In [30]:
tensor=torch.rand(size=(4,4))

print(f"tensor is...\n {tensor}\n")

print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:,0]}")
print(f"Last column: {tensor[:,-1]}")

tensor is...
 tensor([[0.0316, 0.5983, 0.6726, 0.3887],
        [0.6170, 0.5851, 0.3799, 0.0835],
        [0.5812, 0.6894, 0.3459, 0.4387],
        [0.7251, 0.6922, 0.5982, 0.5985]])

First row: tensor([0.0316, 0.5983, 0.6726, 0.3887])
First column: tensor([0.0316, 0.6170, 0.5812, 0.7251])
Last column: tensor([0.3887, 0.0835, 0.4387, 0.5985])


In [32]:
#tensor의 1번째 열의 값을 모두 100으로 치환
tensor[:,1]=10

#tensor의 1번째 행의 값을 모두 0으로 치환
tensor[1]=0


print(f"tensor is...\n {tensor}\n")

tensor is...
 tensor([[ 0.0316, 10.0000,  0.6726,  0.3887],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.5812, 10.0000,  0.3459,  0.4387],
        [ 0.7251, 10.0000,  0.5982,  0.5985]])



In [34]:
#텐서 합치기(Concatination)
concated_tensor = torch.cat([tensor, tensor], dim=1)

print(f"tensor is...\n {concated_tensor}\n")

tensor is...
 tensor([[ 0.0316, 10.0000,  0.6726,  0.3887,  0.0316, 10.0000,  0.6726,  0.3887],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.5812, 10.0000,  0.3459,  0.4387,  0.5812, 10.0000,  0.3459,  0.4387],
        [ 0.7251, 10.0000,  0.5982,  0.5985,  0.7251, 10.0000,  0.5982,  0.5985]])



산술연산

In [37]:
#행렬곱 연산(여기서 tensor.T는 전치행렬)
y1= tensor @ tensor.T

print(f"tensor is...\n {tensor}")
print(f"tensor.T is...\n {tensor.T}\n")

tensor is...
 tensor([[ 0.0316, 10.0000,  0.6726,  0.3887],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.5812, 10.0000,  0.3459,  0.4387],
        [ 0.7251, 10.0000,  0.5982,  0.5985]])
tensor.T is...
 tensor([[ 0.0316,  0.0000,  0.5812,  0.7251],
        [10.0000,  0.0000, 10.0000, 10.0000],
        [ 0.6726,  0.0000,  0.3459,  0.5982],
        [ 0.3887,  0.0000,  0.4387,  0.5985]])



In [38]:
print(f"y1 is...\n {y1}\n")

y1 is...
 tensor([[100.6045,   0.0000, 100.4215, 100.6578],
        [  0.0000,   0.0000,   0.0000,   0.0000],
        [100.4215,   0.0000, 100.6498, 100.8909],
        [100.6578,   0.0000, 100.8909, 101.2418]])



In [ ]:
#단일 요소 텐서(텐서 안 모든 요소들의 합)
agg=tensor.sum()
agg_item=agg.item()

print(agg)
print(agg_item)
print(type(agg_item))

tensor(34.3804)
34.380367279052734
<class 'float'>


In [ ]:
#바꿔치기 연산(솔직히 왜 이렇게 쓰는지 모르겠..)
new_tensor=torch.ones(size=(3,3))
print(f"new tensor is...\n {new_tensor}\n")

new_tensor+=5
print(f"new tensor is...\n {new_tensor}\n")
new_tensor.add_(5)
print(f"new tensor is...\n {new_tensor}\n")

#아... GPU 메모리 상의 효율을 위해 사용함 --> 공식문서의 주의사항에서는 도함수(미분)연산을 할 때 값이 사라지니깐 사용하지 말라함

new tensor is...
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

new tensor is...
 tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]])

new tensor is...
 tensor([[11., 11., 11.],
        [11., 11., 11.],
        [11., 11., 11.]])



### 부록 : 텐서를 넘파이로 변환

In [46]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [47]:
#바꿔치기 연산을 하더라도 넘파이에 유지(내 생각엔 메모리 주소 복사를 해서 스크립트 실행 때마다 변환하는 거 같음..)
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


### 부록 : 넘파이를 텐서로 변환

In [48]:
n = np.ones(5)
print(f"n: {n}")
t = torch.from_numpy(n)
print(f"t: {t}")

n: [1. 1. 1. 1. 1.]
t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [ ]:
#값이 변화되더라도 텐서의 값이 유지(Deep copy)
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
